# Generated by Django 4.2.14 on 2026-07-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả dự án')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang thực hiện'), ('ON_HOLD', 'Tạm dừng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='NOT_STARTED', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='MEDIUM', max_length=20, verbose_name='Độ ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
