# Generated by Django 4.2.14 on 2026-07-26 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên linh kiện')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thành tiền (VNĐ)')),
                ('shop', models.CharField(blank=True, max_length=255, verbose_name='Shop / Cửa hàng mua')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.project', verbose_name='Dự án')),
            ],
        ),
    ]
