# Generated by Django 4.2.14 on 2026-07-26 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên phiên mua sắm')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=20, verbose_name='Trạng thái phiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSessionProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền dự án (VNĐ)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sessions', to='projects.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_projects', to='purchases.purchasesession')),
            ],
            options={
                'unique_together': {('session', 'project')},
            },
        ),
    ]
